name: CI Security Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Получение кода
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Кэш Maven
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # 4. Компиляция и тестирование
      - name: Build with Maven
        run: mvn clean verify -DskipTests=false

      # 5. SAST: SpotBugs анализ кода
      - name: Run SpotBugs
        run: mvn spotbugs:check

      # 6. SCA: Dependency Check (проверка зависимостей)
      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mkdir -p ./dependency-check-data
          mvn -B org.owasp:dependency-check-maven:check \
            -Dnvd.apiKey=$NVD_API_KEY \
            -DdataDirectory=./dependency-check-data \
            -Dformat=HTML \
            -DfailBuildOnCVSS=0 \
            -DsuppressionFile=dependency-check-suppressions.xml \
            -Dossindex.skip=true
        continue-on-error: false


      # 7. Артефакт отчётов
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            target/spotbugsXml.xml
            target/dependency-check-report.html
            target/dependency-check-report.json
